# Cor do Solo

_Alessandro Samuel-Rosa_[^alessandro], _Taciara Zborowski Horst-Heinen_[^taciara]

## Conceitos e definições

A __cor do solo__ é uma qualidade relativa à percepção visual que seres humanos têm do solo. Essa percepção é resultado da impressão que a luz refletida pelo solo produz nos olhos de quem o está observando. Logo, trata-se de uma qualidade perceptível apenas na presença de luz visível, seja ela proveniente de fontes artificiais ou naturais.

A luz visível corresponde aos comprimentos de onda entre cerca de 400 e 700 nm. Essa porção do espectro eletromagnético é popularmente conhecida como espectro óptico ou espectro do visível. Se ignorarmos os principais fatores intervenientes como imperfeições do olho ou cérebro do observador, condições do ambiente circunvizinho, intensidade da luz, e ângulo de incidência e visada, a cor do solo resulta da repartição diferencial dos comprimentos de onda da luz visível incidente entre os fenômenos de absorção, transmissão e reflexão. Essa repartição diferencial é fruto da maneira como os vários constituíntes do solo interagem com a radiação eletromagnética. É a radiação presente nos comprimentos de onda do visível (fótons) que deixam a superfície do solo em maior quantidade, por reflexão ou, inclusive, emissão, que ditam a cor do solo.

## Métodos de determinação

## Fontes de variação

## Padronização

O esquema padronizado de identificação e descrição de métodos de determinação da cor de materiais do solo utilizado no FEBR é apresentado na tabela abaixo. São considerados dois materiais de solo (matriz e manchas), dois estados de umidade (úmido e seco) e duas condições mecânicas (amassada e triturada).

| Código de identificação        | Descrição mínima sugerida |
| ------------------------------ | ------------------------- |
| `cor_matriz_umido_munsell`     | Notação da cor de material de solo [`cor`]. Determinada na matriz do solo [`matriz`]. Amostra em estado de umidade úmido [`umido`]. Expressa utilizando a notação de Munsell® (matiz valor/croma) [`munsell`]. {A DETERMINAÇÃO FOI FEITA NO CAMPO OU EM LABORATÓRIO?} |
| `cor_matriz_seco_munsell`      | Notação da cor de material de solo [`cor`]. Determinada na matriz do solo [`matriz`]. Amostra em estado de umidade seco [seco]. Expressa utilizando a notação de Munsell® (matiz valor/croma) [`munsell`]. {ESPECIFICAR SE A DETERMINAÇÃO FOI FEITA NO CAMPO OU EM LABORATÓRIO} |
| `cor_matriz_amassada_munsell`  | Notação da cor de material de solo [`cor`]. Determinada na matriz do solo [`matriz`]. Amostra em estado de umidade úmido e condição mecânica amassada [`amassada`]. Expressa utilizando a notação de Munsell® (matiz valor/croma) [`munsell`]. {ESPECIFICAR SE A DETERMINAÇÃO FOI FEITA NO CAMPO OU EM LABORATÓRIO} |
| `cor_matriz_triturada_munsell` | Notação da cor de material de solo [`cor`]. Determinada na matriz do solo [`matriz`]. Amostra em estado de umidade seco e condição mecânica triturada [`triturada`]. Expressa utilizando a notação de Munsell® (matiz valor/croma) [`munsell`]. {ESPECIFICAR SE A DETERMINAÇÃO FOI FEITA NO CAMPO OU EM LABORATÓRIO} |
| `cor_mancha_umido_munsell`     | Notação da cor de material de solo [`cor`]. Determinada na mancha do solo [`mancha`]. Amostra em estado de umidade úmido [`umido`]. Expressa utilizando a notação de Munsell® (matiz valor/croma) [`munsell`]. {ESPECIFICAR SE A DETERMINAÇÃO FOI FEITA NO CAMPO OU EM LABORATÓRIO} |

## Exemplo

A tabela a seguir apresenta um exemplo de organização tabular de dados de cor da matriz e manchas de um perfil de solo. Os dados são reais e foram obtidos da descrição morfológica de um perfil de solo classificado como Planossolo Nátrico Órtico vertissólico, localizado no município de Pacaraima, Roraima[@OliveiraEtAl2018b]. A tabela está transposta, com as observações nas colunas e as variáveis nas linhas, para facilitar a visualização e comparação dos códigos de identificação da cores da matriz e machas do perfil de solo.

Dentre os oito horizontes, quatro possuem matriz com duas ou mais cores (Btgn, Btgnv1, Btgnv2 e 2Cgn). Nestes, as cores da matriz ocupam áreas superficiais aproximadamente similares, com distribuição espacial muito complexa, que dificulta a identificação visual de uma cor dominante com credibilidade. Trata-se do padrão multicolorido intricado conhecido como variegado.

|                              | An       | En       | EBn       | Btn       | Btgn      | Btgnv1    | Btgnv2    | 2Cgn     |
| ---------------------------- | -------- | -------- | --------- | --------- | --------- | --------- | --------- | -------- |
| `cor_matriz_umido_munsell_1` | 10YR 5/1 | 10YR 5/1 | 10YR 6/2  | 7,5YR 5/2 | 7,5YR 6/2 | 10YR 4/1  | 10YR 4/1  | 10YR 6/2 |
| `cor_matriz_umido_munsell_2` | -        | -        | -         | -         | 7,5YR 5/2 | 10YR 5/2  | 10YR 5/2  | 10YR 7/2 |
| `cor_matriz_umido_munsell_3` | -        | -        | -         | -         | -         | 10YR 6/2  | 10YR 4/2  | -        |
| `cor_matriz_umido_munsell_4` | -        | -        | -         | -         | -         | 7,5YR 5/8 | 7,5YR 5/6 | -        |
| `cor_matriz_seco_munsell`    | 10YR 6/2 | 10YR 6/1 | -         | -         | -         | -         | -         | -        |
| `cor_mancha_umido_munsell_1` | -        | -        | 7,5YR 5/8 | 7,5YR 5/8 | -         | -         | -         | 10YR 6/8 |
| `cor_mancha_umido_munsell_2` | -        | -        | -         | 7,5YR 4/1 | -         | -         | -         | -        |
| `cor_mancha_umido_munsell_3` | -        | -        | -         | 7,5YR 7/2 | -         | -         | -         | -        |
